version: "3.6"
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    build:
      context: .
      dockerfile: hasura.Dockerfile
    volumes:
      - ./metadata:/hasura-metadata
      - ./migrations:/hasura-migrations
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      WORKFLOW_EXECUTION_INSERTED_WEBHOOK_URL: "http://deli:9090/hasura_event_triggers/workflow_execution_inserted"
      REMOTE_SCHEMA_URL_RESOLVER_SERVICE: "http://resolver-service:7070/query"
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
  stride-songs:
    build:
      context: .
      dockerfile: stride-songs.Dockerfile
      target: dev
    command: air -c air.toml
    volumes:
      - type: bind
        source: .
        target: /project
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      SPOTIFY_CLIENT_ID: abc
      SPOTIFY_CLIENT_SECRET: def
volumes:
  db_data:
