name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Unit tests
        run: go test ./...

      - name: Spin up local environment
        run: scripts/test.sh && scripts/wait-for-hasura.sh

      - name: Integration tests
        run: go test -tags=integration -parallel=1 ./...

      - name: Dump docker-compose logs
        if: failure()
        run: docker-compose logs

  site:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - run: cd demo && yarn install
      - run: cd demo && yarn build
