name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Unit tests
        run: go test ./...

      - name: Spin up local environment
        run: scripts/test.sh && scripts/wait-for-hasura.sh

      - name: Integration tests
        run: go test -tags=integration -parallel=1 ./...

      - name: Dump docker-compose logs
        if: always()
        run: docker-compose logs
